### PR TITLE
Edited guide page

### PR DESCRIPTION
**Pull request by bricekk**
# Pull Request

I made some changes in the guide folder
please check it 🙏🏽

### CODE REVIEW

**Comment by ngdream** [comment]
cool

**Comment by ngdream** [comment]
> # Pull Request
> I made some changes in the guide folder please check it 🙏🏽

telegram ???

**Comment by bricekk** [comment]
?? my username?

**Comment by ngdream** [comment]
> ?? my username?

yep

**Comment by bricekk** [comment]
bricekk

**Pull request merged**
